### PR TITLE
Finished and bonus started

### PR DESCRIPTION
**Pull request by JaviBite**
Finished.
Trying to integrate swagger in order to generate the api documentation (on bonus branch)

### CODE REVIEW

**Comment by fjlopez** [comment]
Review this. If ab2 is the previous state before the POST, you should create a copy of ab2 and test the result of the POST against it! There are similar issues in other calls related to safeness/idepmpotence. 

https://github.com/JaviBite/lab3-restful-ws/blob/301349d97eeee4272ddc8e8e4063860b31b1543b/src/test/java/rest/addressbook/AddressBookServiceTest.java#L121

**Comment by JaviBite** [comment]
I dont understand, the ab2 is the initial state, then I can assert it with the new state in order to check if the state is diferent from the initial one. Why should I create another copy of it?

**Comment by JaviBite** [comment]
I think its ok now

**Comment by fjlopez** [comment]
I can't find your new changes.

**Comment by JaviBite** [comment]
Sorry I didnt push, try now

**Pull request merged**
