### PR TITLE
JWT implemented

### PR DESCRIPTION
**Pull request by AndoniSalcedo**
Now you need a token to access to the route /contacts, to obtain the token a new route has been created /contacts/token.
That token keeps a secret, that it will check if is correct in the call of /contacts

ONLY implemented in route /contacts

### CODE REVIEW

**Comment by fjlopez** [comment]
The solution is close but you need to add some fixes. Your `/token` controller should be something like:
```kotlin
@GET
@Path("/token")
@Produces(MediaType.APPLICATION_JSON)
fun getToken(): ResponseEntity<Void> {
    var issuer = "token"
    var jwt = Jwts.builder().setIssuer(issuer).signWith(SignatureAlgorithm.HS512, "HRlELXqpSBsGHb34E").compact()
   return Response.ok().header(HttpHeaders.AUTHORIZATION, “Bearer ” + jwt).build();
}
```

As it is an `authorization` header, the client will use in future requests to the same site.  See https://swagger.io/docs/specification/authentication/bearer-authentication/

Apply my proposed change and update `getPersons` to process the `authorization` header. Note that if the header is no present or it does not start with `Bearer ` the response status must be 401. Any exception in this scenario should be also considered 401. 

Once you have done this you have the :gift: confirmed.

**Comment by fjlopez** [comment]
Not yet, look at: 

https://github.com/AndoniSalcedo/lab3-restful-ws/blob/408efeacb386a23bd3bb774410bc61f4e1c6fbd2/src/main/kotlin/rest/addressbook/Controller.kt#L55

What should be changed here? Do and you will have the :gift:!

> **Hint**: Use the approach of [The OAuth 2.0 Authorization Framework: Bearer Token Usage. 2 Authenticated Requests](https://datatracker.ietf.org/doc/html/rfc6750#section-2) that makes the most sense.

**Comment by AndoniSalcedo** [comment]
Change the name of the header to Authorization?

**Comment by AndoniSalcedo** [comment]
So, I hope it is finishes

**Comment by fjlopez** [comment]
Well done. :gift: granted.  

I understand why you have used 409 as return code for exceptions in this scenario.  It is used when the request could not be completed due to a conflict with the current state of the target resource. This code is used in situations where the user might be able to resolve the conflict and resubmit the request. It could make sense initially, but this refer to a conflict of versioning (e.g. you PATCH a representation with a change that can't be applied). So, why is the best approach in these cases? Your code shows that exception if related to the handling of the Authorization token. In these cases is advisable to use the general purpose "blame the client" 400 status code because the server cannot process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

**Pull request merged**
