### PR TITLE
PR Luis García 

### PR DESCRIPTION
**Pull request by luisgg98**
Good morning!
I've completed the tests and added it branch to Travis.
Please check this out and please tell me if you miss something.

### CODE REVIEW

**Comment by fjlopez** [comment]
I just miss a note about if you have found the subtle bug or not. Just add a comment to the code (found) or this conversation (not found). Next, I will merge your PR and send you an email with relevant information about the bug.

**Comment by luisgg98** [comment]
No problem! I'll dig on the code to find the bug

**Comment by fjlopez** [comment]
Did you find the bug?

**Comment by luisgg98** [comment]
Yes, I finally found it, sorry I didn't realize at the first time

**Pull request merged**
