### PR TITLE
Primary goal

### PR DESCRIPTION
**Pull request by topopelon**

### CODE REVIEW

**Comment by fjlopez** [comment]
@topopelon Have you done some advance on this? If you think that the tests are complete you must also add an explanation.

**Comment by topopelon** [comment]
No I couldn't do it. I will have it this week.

**Comment by fjlopez** [comment]
@topopelon Ready for review?

**Comment by topopelon** [comment]
Yup. Ready for review.

**Comment by fjlopez** [comment]
**PR accepted**

**Pull request merged**
